An example how to use an image as a 3d viewport
jkb0o/belly pull request #38
Opened 2023-02-05 20:52 UTC by bekraoui

This is an example how to use an image as a 3d viewport. remarq: for the now:

- the cube is not rotating (i dont know why yet) it seems like the <img> is not updating.
- applying padding to the <body> a margin  to the <img> in the css will cause the cube to drift out of the image.

it is a custumization of the bevy render to texture exemple. with more simplificaiton and a rotationg cube (not rotating yet :) ) inside the viewport.

2023-02-05 20:56 UTC, bekraoui commented
hi, this is a screenshot of the result:

![screenshot_0](https://user-images.githubusercontent.com/38771411/216845360-cc323e25-2c4d-4b7c-9da4-8a1f2afe2921.png)

2023-02-06 08:54 UTC, jkb0o commented
Wow! Looks nice! Thanks! I'll check it and leave comments today or tomorrow.

2023-02-06 11:28 UTC, bekraoui commented
Thank you for this awesome project. Take your time

2023-02-17 17:33 UTC, jkb0o requested changes
It looks good and will work like a charm after resolving comments.

Also, It would be cool if you do `cargo fmt`

Thank you! And sorry it took so many days!

2023-02-17 17:33 UTC, jkb0o commented on examples/image-render-to-texture.rs
> +    .insert(viewport_pass_layer);
I found that the render UICamera doesn't respects the RenderLayer: https://github.com/bevyengine/bevy/issues/6069 and the resulting ui renders with artifacts (if I change background-color for image, for example).

Provided in the issue workaround works like a charm, so my suggestion is to notice the bug in example and add
```rust
.insert(UiCameraConfig { show_ui: false })
```

2023-02-17 17:33 UTC, jkb0o commented on examples/image-render-to-texture.rs
> +    //set the width and the height of the viewport
I suggest to uncomment stylesheets and provide `background-color` and relative sizes, so user can resize the window and see how rendered widget behaves. For me (after fixing bug from previous comment) it works like a charm. I've tried with this styles:
```css
#viewport {
  margin: 50px; 
  width: 50%; 
  height: 50%; 
  background-color: grey;
}
```

2023-02-17 17:35 UTC, jkb0o commented
And I didn't met issues with cube: it is rotates and doesn't drift.

2023-02-17 20:29 UTC, bekraoui commented
The drifting happens when i uncomment the style. I will try it again and make the changes you recomanded as soon as possible (probably in 2 or 3 days)

2023-02-22 03:05 UTC, bekraoui commented
it works perfectly. thank you
on the other side cargo fmt does not seem to make any change; by the way i'm new to rust and and developping UI apps so hope to learn from you :).

2023-03-01 08:37 UTC, jkb0o approved these changes

2023-03-01 08:38 UTC, merged

2023-03-01 08:39 UTC, jkb0o commented
Thank you!